# Generated by Django 6.0 on 2026-01-11 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_user_subscribed_articles_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
