# Generated by Django 6.0 on 2026-03-05 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='user',
        ),
        migrations.AddField(
            model_name='publisher',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='independent_newsletters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
