# Generated by Django 6.0 on 2026-03-08 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_publisher_user_publisher_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='approved_by_editor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
