# Generated by Django 6.0 on 2026-01-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_articles',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='news.article'),
        ),
    ]
