# Generated by Django 6.0 on 2026-02-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='journalists',
        ),
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
