# Generated by Django 6.0 on 2026-03-08 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_article_approved_by_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
